// flask-react/client/Pages/Home/index.js
import React, {useEffect, useState} from 'react';
import { Table } from 'react-bootstrap';

export default function Home() {
  const [people, setPeople] = useState([])
  
  async function getPeople() {
    const response = await fetch('/api/people');
    setPeople(await response.json())
  }

  useEffect(() => {
    getPeople();
  }, []);

  return <>
    <p>This table data is loaded through a fetch call to the flask backend!</p>
    <Table hover>
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        {people.map(person => (
          <tr key={person.id}>
            <td>{person.id}</td>
            <td>{person.name}</td>
            <td>{person.status}</td>
          </tr>
        ))}
      </tbody>
    </Table>
  </>
}

// flask-vue/client/pages/Home.vue
<template>
    <div>
        <p>This table data is loaded through a fetch call to the flask backend!</p>
        <b-table hover :items="people" :fields="fields">
            <template v-slot:cell(nameLink)="data">
                <router-link :to="`/user/${data.item.id}`">{{ data.item.name }}</router-link>
            </template>
        </b-table>
    </div>
</template>
<script>
export default {
    name: 'Home',

    components: {
    },

    data() {
        return {
            fields: [
                {
                    key: 'id',
                    label: '#'
                }, 
                {
                    key: 'nameLink',
                    label: 'Name'
                }, 
                {
                    key: 'status',
                    label: 'Status'
                }
            ],
            people: []
        }
    },

    async mounted() {
        const response = await fetch('/api/people');
        this.people = await response.json();
    }
}
</script>
