// flask-react/client/App/Nav.js
import React from 'react';
import { Navbar, Nav } from 'react-bootstrap';
import { Link, useLocation } from 'react-router-dom';

export default function() {
  const { pathname } = useLocation();
  return (
    <Navbar bg="light" expand="lg">
      <Navbar.Brand as={Link} href="/" to="/">Flask React</Navbar.Brand>
      <Navbar.Toggle aria-controls="basic-navbar-nav" />
      <Navbar.Collapse id="basic-navbar-nav">
        <Nav activeKey={pathname}>
          <Nav.Link as={Link} href="/" to="/">Home</Nav.Link>
          <Nav.Link as={Link} href="/about" to="/about">About</Nav.Link>
        </Nav>
      </Navbar.Collapse>
    </Navbar>
  );
}

// flask-vue/client/Nav.vue
<template>
  <b-navbar toggleable="lg" type="light" variant="light">
    <b-navbar-brand to="/">Flask Vue</b-navbar-brand>
    <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>
    <b-collapse id="nav-collapse" is-nav>
        <b-navbar-nav active="/">
            <b-nav-item to="/" v-bind:active="$route.path === '/'">Home</b-nav-item>
            <b-nav-item to="/about" v-bind:active="$route.path === '/about'">About</b-nav-item>
        </b-navbar-nav>
    </b-collapse>
  </b-navbar>
</template>
<script>
export default {
  name: 'Nav',

  components: {
  },
}
</script>
